# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

do ->
  scrollContainer = document.querySelector('.scrollable')
  scrollContentWrapper = document.querySelector('.scrollable .content-wrapper')
  scrollContent = document.querySelector('.scrollable .content')
  contentPosition = 0
  scrollerBeingDragged = false
  scroller = undefined
  topPosition = undefined
  scrollerHeight = undefined

  calculateScrollerHeight = ->
    # *Calculation of how tall scroller should be
    visibleRatio = scrollContainer.offsetHeight / scrollContentWrapper.scrollHeight
    visibleRatio * scrollContainer.offsetHeight

  moveScroller = (evt) ->
    # Move Scroll bar to top offset
    scrollPercentage = evt.target.scrollTop / scrollContentWrapper.scrollHeight
    topPosition = scrollPercentage * (scrollContainer.offsetHeight - 5)
    # 5px arbitrary offset so scroll bar doesn't move too far beyond content wrapper bounding box
    scroller.style.top = topPosition + 'px'
    return

  startDrag = (evt) ->
    normalizedPosition = evt.pageY
    contentPosition = scrollContentWrapper.scrollTop
    scrollerBeingDragged = true
    return

  stopDrag = (evt) ->
    scrollerBeingDragged = false
    return

  scrollBarScroll = (evt) ->
    if scrollerBeingDragged == true
      mouseDifferential = evt.pageY - normalizedPosition
      scrollEquivalent = mouseDifferential * scrollContentWrapper.scrollHeight / scrollContainer.offsetHeight
      scrollContentWrapper.scrollTop = contentPosition + scrollEquivalent
    return

  createScroller = ->
    # *Creates scroller element and appends to '.scrollable' div
    # create scroller element
    scroller = document.createElement('div')
    scroller.className = 'scroller'
    # determine how big scroller should be based on content
    scrollerHeight = calculateScrollerHeight()
    if scrollerHeight / scrollContainer.offsetHeight < 1
      # *If there is a need to have scroll bar based on content size
      scroller.style.height = scrollerHeight + 'px'
      # append scroller to scrollContainer div
      scrollContainer.appendChild scroller
      # show scroll path divot
      scrollContainer.className += ' showScroll'
      # attach related draggable listeners
      scroller.addEventListener 'mousedown', startDrag
      window.addEventListener 'mouseup', stopDrag
      window.addEventListener 'mousemove', scrollBarScroll
    return

  createScroller()
  # *** Listeners ***
  scrollContentWrapper.addEventListener 'scroll', moveScroller
  return

# ---
# generated by js2coffee 2.0.4
